### ISSUE TITLE
./configure failed to locate libcap on Ubuntu14.04

### ISSUE THREAD

**Issue by LongRail** [deeponion/deeponion-legacy#63]
libcap installed by 'apt-get install libcap-dev' as well as other dependencies listed in documentation

./configure --without-gui
.......
checking whether the Boost::Unit_Test_Framework library is available... yes
checking for dynamic linked boost test... yes
checking for LIBEVENT... yes
checking for ZLIB... yes
checking for LIBSECCOMP... yes
checking for LIBCAP... no
configure: error: libcap not found
 
so that, libseccomp detected but libcap not.

**Comment by LongRail** [comment]
Similar issue here : https://github.com/vergecurrency/VERGE/issues/459

**Comment by brakmic** [comment]
It's an Ubuntu 14.04 problem.

**Comment by deeponion** [comment]
Yes it is an Ubuntu 14.04 issue. You can manually patch it. It somehow missed the pkgconfig file. Create this file: /usr/lib/x86_64-linux-gnu/pkgconfig/libcap-dev.pc, you can copy from libseccomp-dev.pc, then edit it and make sure the package name etc correct.
Re-run ./configure, it should be fine.

**Comment by LongRail** [comment]
Thanks! 
Creation of this file: /usr/lib/x86_64-linux-gnu/pkgconfig/libcap.pc works for me. 
File content:

```
#
# This is manual fix for missing libcap.pc file
#

prefix=/usr
libdir=/usr/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: libcap
Description: Some useful library
URL: http://libseccomp.sf.net
Version: 2.24
Cflags: -I${includedir}
Libs: -L${libdir} -lcap

```

**Comment by LongRail** [comment]
But it's not the end: 
make failed.  (again I build on Ubuntu 14.04 with Boost 1.54 installed)
........
  CXXLD    DeepOniond
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[1]: *** [DeepOniond] Error 1

Looks like similar to https://github.com/cryptofun/honey/issues/19

**Comment by brakmic** [comment]
It seems you're trying to link with system-installed boost. 
Inform your **configure** by adding a **-I/YOUR/BOOST/PATH** flag.

**Comment by LongRail** [comment]
Yes, that's right. I have installed Boost via 'sudo apt-get install'. And that was fine for DeepOniond 1.4.3.0
Shall I install another Boost now? Do you think the patch proposed in link makes sense?

**Comment by brakmic** [comment]
I don't know what's on your system, it's up to you to configure it as you prefer. For the current version, please follow our install config. We use boost 1.57.

**Comment by LongRail** [comment]
Solved.
In order to build on Ubuntu 14.04 you have to upgrade Boost to 1.57. Upgrade to latest Boost (1.66) draws some incompatibility with current code.
For one who still want to use Ubuntu 14.04 the recipe is below:
- Download and unpack Boost 1.57
- Configure only needed libs 
```
./bootstrap.sh --with-libraries=chrono,date_time,filesystem,iostreams,program_options,regex,system,thread,test --without-icu
./b2 install --prefix=~/boostlibs
```
- Configure deeponion client

```
./configure --without-gui --with-boost=~/boostlibs --with-boost-libdir=~/boostlibs/lib
make
```
- Add your non-standard Boost library location to Ubuntu library search path
```
sudo /bin/bash -c 'echo "~/boostlibs/lib" > /etc/ld.so.conf.d/boost.conf'
sudo ldconfig
```
Et voila!

**Comment by brakmic** [comment]
Thanks @LongRail 

I added your solution to our *build_unix* [doc](https://github.com/deeponion/deeponion/blob/master/doc/build-unix.md).

Cheers,

**Comment by bx1805** [comment]
undefined reference to `ThemeFancyPurple::ThemeFancyPurple()'
deeponion.git.20180916

  OBJCXXLD qt/DeepOnion-qt
qt/libbitcoinqt.a(qt_libbitcoinqt_a-thememanager.o): In function `ThemeManager::ThemeManager()':
thememanager.cpp:(.text+0x786): undefined reference to `ThemeFancyPurple::ThemeFancyPurple()'
collect2: error: ld returned 1 exit status

Patch:
--- deeponion.git.20180916.orig/src/Makefile.qt.include 2018-09-16 14:01:01.991115697 +0300
+++ deeponion.git.20180916/src/Makefile.qt.include      2018-09-16 14:04:52.134812173 +0300
@@ -135,6 +135,7 @@
   qt/sendmessagesentry.h \
   qt/signverifymessagedialog.h \
   qt/theme.h \
+  qt/themefancypurple.h \
   qt/themeoriginaldark.h \
   qt/themeoriginallight.h \
   qt/thememanager.h \
@@ -244,6 +245,7 @@
   qt/plugins/mrichtexteditor/mrichtextedit.cpp \
   qt/signverifymessagedialog.cpp \
   qt/theme.cpp \
+  qt/themefancypurple.cpp \
   qt/themeoriginaldark.cpp \
   qt/themeoriginallight.cpp \
   qt/thememanager.cpp \

**Comment by bx1805** [comment]
undefined reference to `ThemeFancyPurple::ThemeFancyPurple()'
deeponion.git.20180916

OBJCXXLD qt/DeepOnion-qt
qt/libbitcoinqt.a(qt_libbitcoinqt_a-thememanager.o): In function ThemeManager::ThemeManager()': thememanager.cpp:(.text+0x786): undefined reference toThemeFancyPurple::ThemeFancyPurple()'
collect2: error: ld returned 1 exit status

Patch:
```diff
--- deeponion.git.20180916.orig/src/Makefile.qt.include 2018-09-16 14:01:01.991115697 +0300
+++ deeponion.git.20180916/src/Makefile.qt.include      2018-09-16 14:04:52.134812173 +0300
@@ -135,6 +135,7 @@
   qt/sendmessagesentry.h \
   qt/signverifymessagedialog.h \
   qt/theme.h \
+  qt/themefancypurple.h \
   qt/themeoriginaldark.h \
   qt/themeoriginallight.h \
   qt/thememanager.h \
@@ -244,6 +245,7 @@
   qt/plugins/mrichtexteditor/mrichtextedit.cpp \
   qt/signverifymessagedialog.cpp \
   qt/theme.cpp \
+  qt/themefancypurple.cpp \
   qt/themeoriginaldark.cpp \
   qt/themeoriginallight.cpp \
   qt/thememanager.cpp \
