### ISSUE TITLE
OpenSSL & showMeDetailsButton

### ISSUE THREAD

**Issue by dragononcrypto** [deeponion/deeponion-legacy#121]
I realise the software isn't supported for Ubuntu 18.04 LTS yet, but here is a bug report anyway. This is with libssl1.0-dev, not libssl-dev (1.1), but it still doesn't build. When trying to build with libssl1.1-dev, there are different errors related to BIGNUM for src/key.h, even though these lines were since removed, so I can't remove them as previously suggested by brakmic sometime ago for Raspberry Pi.

I've also tried with the --with-openssl-dir= variable to a OpenSSL1.0 directory built from source, when configuring as well as editing the Makefile, but unfortunately it get's stuck on tor/src. I'm giving up for now unless I find solutions from the reference below, or unless you want to shout suggestions at me and I'll try them. I'd be happy to receive any extra pieces for this puzzle.

src/common/libor-crypto.a(crypto.o): In function `crypto_force_rand_ssleay':
crypto.c:(.text+0x16): undefined reference to `RAND_SSLeay'
src/common/libor-crypto.a(crypto.o): In function `crypto_early_init.part.13':
crypto.c:(.text+0x2ba0): undefined reference to `ERR_load_crypto_strings'
crypto.c:(.text+0x2ba5): undefined reference to `OPENSSL_add_all_algorithms_noconf'
crypto.c:(.text+0x2baf): undefined reference to `SSLeay'
crypto.c:(.text+0x2bb9): undefined reference to `SSLeay_version'
src/common/libor-crypto.a(crypto.o): In function `crypto_global_init':
crypto.c:(.text+0x2ea0): undefined reference to `ENGINE_get_default_ECDH'
crypto.c:(.text+0x2eb4): undefined reference to `ENGINE_get_default_ECDSA'
src/common/libor-crypto.a(crypto.o): In function `crypto_global_cleanup':
crypto.c:(.text+0x30e5): undefined reference to `EVP_cleanup'
crypto.c:(.text+0x30f1): undefined reference to `ERR_free_strings'
crypto.c:(.text+0x314a): undefined reference to `ENGINE_cleanup'
crypto.c:(.text+0x3159): undefined reference to `CRYPTO_cleanup_all_ex_data'
src/common/libor-crypto.a(crypto_openssl_mgt.o): In function `crypto_openssl_get_version_str':
crypto_openssl_mgt.c:(.text+0x1ab): undefined reference to `SSLeay_version'
src/common/libor-crypto.a(crypto_openssl_mgt.o): In function `setup_openssl_threading':
crypto_openssl_mgt.c:(.text+0x249): undefined reference to `CRYPTO_num_locks'
crypto_openssl_mgt.c:(.text+0x2a4): undefined reference to `CRYPTO_set_locking_callback'
crypto_openssl_mgt.c:(.text+0x2b0): undefined reference to `CRYPTO_THREADID_set_callback'
src/common/libor-crypto.a(crypto_openssl_mgt.o): In function `tor_set_openssl_thread_id':
crypto_openssl_mgt.c:(.text+0xc9): undefined reference to `CRYPTO_THREADID_set_numeric'
src/common/libor-crypto.a(tortls.o): In function `tor_tls_classify_client_ciphers':
tortls.c:(.text+0x416): undefined reference to `sk_value'
tortls.c:(.text+0x477): undefined reference to `sk_num'
tortls.c:(.text+0x596): undefined reference to `sk_value'
tortls.c:(.text+0x5c7): undefined reference to `sk_num'
tortls.c:(.text+0x5fb): undefined reference to `sk_value'
tortls.c:(.text+0x616): undefined reference to `sk_num'
src/common/libor-crypto.a(tortls.o): In function `tor_tls_server_info_callback':
tortls.c:(.text+0x80c): undefined reference to `SSL_state'
src/common/libor-crypto.a(tortls.o): In function `tor_tls_init':
tortls.c:(.text+0x1269): undefined reference to `SSL_library_init'
tortls.c:(.text+0x126e): undefined reference to `SSL_load_error_strings'
tortls.c:(.text+0x1273): undefined reference to `SSLeay'
tortls.c:(.text+0x1354): undefined reference to `SSL_get_ex_new_index'
src/common/libor-crypto.a(tortls.o): In function `tor_tls_handshake':
tortls.c:(.text+0x35bc): undefined reference to `SSL_state'
tortls.c:(.text+0x35ea): undefined reference to `SSL_state'
src/common/libor-crypto.a(tortls.o): In function `tor_tls_verify':
tortls.c:(.text+0x3c56): undefined reference to `sk_num'
tortls.c:(.text+0x3c77): undefined reference to `sk_value'
src/common/libor-crypto.a(aes.o): In function `aes_cipher_free_':
aes.c:(.text+0xde): undefined reference to `EVP_CIPHER_CTX_cleanup'
collect2: error: ld returned 1 exit status
Makefile:4688: recipe for target 'src/or/tor' failed
make[2]: *** [src/or/tor] Error 1
make[2]: Leaving directory '/home/dragon/deeponion/tor'
Makefile:3437: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/dragon/deeponion/tor'
Makefile:542: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Reference: https://github.com/zcoinofficial/zcoin/issues/193

**Comment by nezero** [comment]
Have you seen the Debian 9 build doc? https://github.com/deeponion/deeponion/blob/master/doc/build-debian-9.md It uses a Jessie backport for SSL.

**Comment by dragononcrypto** [comment]
Yes, I wrote the Tails tutorial that this method is based on ;-) Unfortunately unlike in Debian 9 installing 1.1 over 1.0 will scrap a lot of the base system in the process.

I have libssl1.0-dev installed (1.0.2**n**-1ubuntu5) but I just tried to re-build with 1.0.2**g**-1ubuntu13.5 from Ubuntu 17.10 artful that actually helped. Thanks!

I then [got this error](https://github.com/deeponion/deeponion/issues/89) and changed _src/key.h_ to the pi branch which successfully seems to of built the openssl related components. I'm guessing this means it would work with bionic libssl-dev (1.1) as well, which would be the cleaner approach, but would need to check.

However now I have this error I've never seen before, search engines aren't helping me either:

> Making all in tor
> make[1]: Entering directory '/home/dragon/deeponion/tor'
> make  all-am
> make[2]: Entering directory '/home/dragon/deeponion/tor'
> make[2]: Leaving directory '/home/dragon/deeponion/tor'
> make[1]: Leaving directory '/home/dragon/deeponion/tor'
> Making all in src
> make[1]: Entering directory '/home/dragon/deeponion/src'
>   OBJCXXLD qt/DeepOnion-qt
> qt/libbitcoinqt.a(qt_libbitcoinqt_a-rpcconsole.o): In function `RPCConsole::on_showMeDetailsButton_clicked()':
> /home/dragon/deeponion/src/qt/rpcconsole.cpp:643: undefined reference to `BlockchainDialog::BlockchainDialog(QWidget*)'
> /home/dragon/deeponion/src/qt/rpcconsole.cpp:644: undefined reference to `BlockchainDialog::setLabelText(WalletModel*)'
> /home/dragon/deeponion/src/qt/rpcconsole.cpp:643: undefined reference to `BlockchainDialog::~BlockchainDialog()'
> /home/dragon/deeponion/src/qt/rpcconsole.cpp:643: undefined reference to `BlockchainDialog::~BlockchainDialog()'
> collect2: error: ld returned 1 exit status
> Makefile:2244: recipe for target 'qt/DeepOnion-qt' failed
> make[1]: *** [qt/DeepOnion-qt] Error 1
> make[1]: Leaving directory '/home/dragon/deeponion/src'
> Makefile:542: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

2nd Edit: Assuming it might be related to [this push](https://github.com/deeponion/deeponion/commit/a2cfa6761aebe7c53727be7d71984fc9bbc7124f)?

**Comment by dragononcrypto** [comment]
Solved! I removed the relevant lines referencing showMeDetailsButton from the recent update and it built without any errors:

src/qt/forms/rpcconsole.ui
src/qt/rpcconsole.cpp
src/qt/rpcconsole.h 

Do you want me to make push request for now to reverse these changes? I don't know C well enough to fix I'm afraid. Hope this info helps, thanks again for pointing me in the right direction initially.

Edit: Think @aitorp6 has already addressed this, amazing work!
Reference: https://github.com/deeponion/deeponion/pull/122
